"use strict";
const STORAGE_KEY="classroomDataV1",UNDO_BUMP_KEY="classroomUndoBumpV2",UNDO_IMPORT_KEY="classroomUndoImportV2";
const emptyData={lessons:[],materials:[],calendarEvents:[],students:[],teachingMemory:[],templates:[],imports:[]};
let data=loadData(),weekStart=getMonday(new Date()),pendingImport=null;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const viewMeta={dashboard:["Workspace","Teaching overview"],calendar:["Plan and adjust","Weekly planner"],sessions:["Personalized learning","One-on-one sessions"],library:["Centralized resources","Resource library"],import:["Local personalization","Import center"]};
const categoryConfig={
 lesson:{label:"Lessons / schedule",collection:"lessons",required:["title","date"],fields:{title:"Lesson title",date:"Date",time:"Start time",duration:"Duration",type:"Lesson type",learner:"Learner / group",objective:"Objective",notes:"Notes",materialUrl:"Material URL"}},
 calendar:{label:"School calendar",collection:"calendarEvents",required:["title","date"],fields:{title:"Event title",date:"Start date",endDate:"End date",type:"Event type",notes:"Notes"}},
 library:{label:"Library resources",collection:"materials",required:["title"],fields:{title:"Title",type:"Resource type",url:"URL",grade:"Grade",skill:"Skill",topic:"Topic",unit:"Unit / learner",tags:"Tags",notes:"Notes"}},
 student:{label:"Students / learners",collection:"students",required:["name"],fields:{name:"Name",grade:"Grade",group:"Class / group",goals:"Goals",interests:"Interests",notes:"Notes"}},
 memory:{label:"Teaching memory",collection:"teachingMemory",required:["learner","observation"],fields:{learner:"Learner",date:"Date",category:"Memory category",observation:"Observation",nextStep:"Next step",tags:"Tags"}},
 template:{label:"Lesson templates",collection:"templates",required:["title"],fields:{title:"Template title",type:"Type",grade:"Grade",skill:"Skill",objective:"Objective",activities:"Activities",materials:"Materials",tags:"Tags"}}
};
const aliases={
 title:["title","lesson title","lesson","name","resource title","event","event title","课程","课程名称","标题","活动名称","资源名称","事件"],
 date:["date","lesson date","class date","start date","日期","上课日期","开始日期","时间"],endDate:["end date","结束日期"],time:["time","start time","class time","上课时间","开始时间"],duration:["duration","minutes","length","时长","分钟"],type:["type","lesson type","resource type","category","类型","类别"],learner:["learner","student","group","class","student name","学习者","学生","班级","小组"],objective:["objective","goal","learning objective","目标","学习目标"],notes:["notes","note","description","备注","说明"],materialUrl:["material url","resource url","link","url","材料链接","资源链接"],url:["url","link","website","drive","链接","网址"],grade:["grade","year level","年级"],skill:["skill","language skill","技能","语言技能"],topic:["topic","theme","主题"],unit:["unit","unit or learner","单元"],tags:["tags","tag","标签"],name:["name","student name","learner name","姓名","学生姓名"],group:["group","class","homeroom","班级","小组"],goals:["goals","goal","learning goals","目标","学习目标"],interests:["interests","preferences","兴趣","偏好"],category:["category","memory type","类别","记录类型"],observation:["observation","record","memory","teacher note","观察","教学记录","表现"],nextStep:["next step","follow up","recommendation","下一步","后续建议"],activities:["activities","activity","procedures","活动","教学活动"],materials:["materials","resources","材料","资源"]
};
function normalizeData(raw){const d={...structuredClone(emptyData),...(raw||{})};Object.keys(emptyData).forEach(k=>{if(!Array.isArray(d[k]))d[k]=[]});d.lessons=d.lessons.map(x=>({...x,id:x.id||crypto.randomUUID(),duration:Number(x.duration)||60,time:x.time||"09:00",type:x.type||"Class"}));d.materials=d.materials.map(x=>({...x,id:x.id||crypto.randomUUID(),unit:x.unit||x.tag||"",tags:x.tags||"",createdAt:Number(x.createdAt)||Date.now()}));return d}
function loadData(){try{const saved=localStorage.getItem(STORAGE_KEY);return normalizeData(saved?JSON.parse(saved):emptyData)}catch{return normalizeData(emptyData)}}
function persist(message="Saved"){localStorage.setItem(STORAGE_KEY,JSON.stringify(data));renderAll();showToast(message)}
function toISODate(date){const local=new Date(date.getTime()-date.getTimezoneOffset()*60000);return local.toISOString().slice(0,10)}
function parseLocalDate(v){return new Date(`${v}T12:00:00`)}
function getMonday(date){const d=new Date(date),day=d.getDay(),diff=d.getDate()-day+(day===0?-6:1);d.setDate(diff);d.setHours(12,0,0,0);return d}
function addDays(date,n){const d=new Date(date);d.setDate(d.getDate()+n);return d}
function normalizeDate(v){if(v instanceof Date&&!isNaN(v))return toISODate(v);const s=String(v??"").trim();if(!s)return"";if(/^\d{4}-\d{1,2}-\d{1,2}$/.test(s)){const [y,m,d]=s.split("-").map(Number);return `${y}-${String(m).padStart(2,"0")}-${String(d).padStart(2,"0")}`}const date=new Date(s);return isNaN(date)?"":toISODate(date)}
function normalizeTime(v){const s=String(v??"").trim();if(!s)return"09:00";const m=s.match(/^(\d{1,2}):(\d{2})/);if(m)return`${String(Math.min(23,Number(m[1]))).padStart(2,"0")}:${m[2]}`;const date=new Date(`2000-01-01 ${s}`);return isNaN(date)?"09:00":`${String(date.getHours()).padStart(2,"0")}:${String(date.getMinutes()).padStart(2,"0")}`}
function formatTime(t){const[h,m]=String(t||"09:00").split(":").map(Number);return new Intl.DateTimeFormat("en-US",{hour:"numeric",minute:"2-digit"}).format(new Date(2020,1,1,h,m))}
function sortedLessons(){return[...data.lessons].sort((a,b)=>`${a.date}T${a.time}`.localeCompare(`${b.date}T${b.time}`))}
function escapeHTML(v=""){return String(v).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#039;",'"':"&quot;"}[c]))}
function safeUrl(v){try{const u=new URL(v);return["http:","https:"].includes(u.protocol)?u.href:"#"}catch{return"#"}}
function switchView(name){const view=$(`#${name}View`);if(!view)return;$$('.view').forEach(v=>v.classList.remove('active'));$$('.nav-item').forEach(n=>n.classList.toggle('active',n.dataset.view===name));view.classList.add('active');$("#viewEyebrow").textContent=viewMeta[name][0];$("#viewTitle").textContent=viewMeta[name][1];window.scrollTo({top:0,behavior:"smooth"})}
function renderAll(){renderDashboard();renderWeek();renderSessions();renderLibrary();renderImportHistory();updateUndoButtons()}
function renderDashboard(){const today=toISODate(new Date()),todayLessons=sortedLessons().filter(x=>x.date===today);$("#todayHeading").textContent=new Intl.DateTimeFormat("en-US",{weekday:"long",month:"long",day:"numeric"}).format(new Date());$("#todaySummary").textContent=todayLessons.length?`${todayLessons.length} lesson${todayLessons.length===1?"":"s"} planned today. First lesson: ${formatTime(todayLessons[0].time)}.`:"No lessons are scheduled today. Add lessons manually or import a schedule.";const end=addDays(weekStart,7),week=data.lessons.filter(x=>{const d=parseLocalDate(x.date);return d>=weekStart&&d<end});$("#weekLessonCount").textContent=week.length;$("#oneOnOneCount").textContent=week.filter(x=>x.type==="One-on-one").length;$("#materialCount").textContent=data.materials.length;$("#importCount").textContent=data.imports.length;const now=`${today}T${new Date().toTimeString().slice(0,5)}`,up=sortedLessons().filter(x=>`${x.date}T${x.time}`>=now);$("#upcomingList").innerHTML=up.slice(0,4).map(x=>{const d=parseLocalDate(x.date);return`<article class="upcoming-card"><div class="date-badge"><span>${d.toLocaleDateString("en-US",{month:"short"})}</span><strong>${d.getDate()}</strong></div><div><h4>${escapeHTML(x.title)}</h4><p>${formatTime(x.time)} · ${escapeHTML(x.learner||x.type)}</p></div><span class="type-pill">${escapeHTML(x.type)}</span></article>`}).join("")||'<div class="empty-state">No upcoming lessons yet.</div>';const recent=[...data.materials].sort((a,b)=>b.createdAt-a.createdAt).slice(0,4);$("#recentMaterials").innerHTML=recent.map(x=>`<a class="resource-item" href="${safeUrl(x.url)}" target="_blank" rel="noreferrer"><span class="resource-icon">↗</span><span><strong>${escapeHTML(x.title)}</strong><span>${escapeHTML(x.type||"Resource")} · ${escapeHTML(x.unit||"General")}</span></span></a>`).join("")||'<div class="empty-state">No resources saved yet.</div>'}
function renderWeek(){const end=addDays(weekStart,6);$("#weekRange").textContent=`${weekStart.toLocaleDateString("en-US",{month:"short",day:"numeric"})} – ${end.toLocaleDateString("en-US",{month:"short",day:"numeric",year:"numeric"})}`;const today=toISODate(new Date()),names=["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"];$("#weekGrid").innerHTML=names.map((name,i)=>{const date=addDays(weekStart,i),key=toISODate(date),items=sortedLessons().filter(x=>x.date===key),cards=items.map(x=>`<article class="lesson-card ${String(x.type).toLowerCase().replaceAll(" ","-")}"><span class="eyebrow">${formatTime(x.time)} · ${x.duration} min</span><h4>${escapeHTML(x.title)}</h4><p>${escapeHTML(x.learner||x.type)}</p><div class="lesson-card-actions"><button class="mini-button" data-edit-lesson="${x.id}">Edit</button><button class="mini-button" data-bump-lesson="${x.id}">Bump</button></div></article>`).join("")||'<div class="empty-day">No lessons</div>';return`<section class="day-column ${key===today?"today":""} ${i>=5?"weekend":""}"><div class="day-heading"><span>${name}</span><strong>${date.getDate()}</strong></div><div class="day-lessons">${cards}</div></section>`}).join("");$$('[data-edit-lesson]').forEach(b=>b.addEventListener('click',()=>openLessonDialog(b.dataset.editLesson)));$$('[data-bump-lesson]').forEach(b=>b.addEventListener('click',()=>openBumpDialog(b.dataset.bumpLesson)))}
function renderSessions(){const s=sortedLessons().filter(x=>x.type==="One-on-one");$("#sessionList").innerHTML=s.map(x=>`<article class="session-card"><div class="session-card-top"><div><span class="eyebrow">${escapeHTML(x.learner||"Individual learner")}</span><h4>${escapeHTML(x.title)}</h4><span class="session-date">${parseLocalDate(x.date).toLocaleDateString("en-US",{weekday:"long",month:"long",day:"numeric"})} · ${formatTime(x.time)}</span></div><button class="icon-button" data-edit-lesson="${x.id}">✎</button></div><dl><div><dt>Goal</dt><dd>${escapeHTML(x.objective||"No objective added yet.")}</dd></div><div><dt>Plan and notes</dt><dd>${escapeHTML(x.notes||"No notes added yet.")}</dd></div></dl></article>`).join("")||'<div class="empty-state">No one-on-one sessions yet.</div>';$$('#sessionList [data-edit-lesson]').forEach(b=>b.addEventListener('click',()=>openLessonDialog(b.dataset.editLesson)))}
function renderLibrary(){const q=($("#materialSearch")?.value||"").toLowerCase(),type=$("#materialTypeFilter")?.value||"all",skill=$("#materialSkillFilter")?.value||"all";const skills=[...new Set(data.materials.map(x=>x.skill).filter(Boolean))].sort();const sel=$("#materialSkillFilter"),current=sel.value;sel.innerHTML='<option value="all">All skills</option>'+skills.map(x=>`<option>${escapeHTML(x)}</option>`).join("");sel.value=skills.includes(current)?current:"all";const filtered=[...data.materials].sort((a,b)=>b.createdAt-a.createdAt).filter(x=>type==="all"||x.type===type).filter(x=>skill==="all"||x.skill===skill).filter(x=>`${x.title} ${x.grade} ${x.skill} ${x.topic} ${x.unit} ${x.tags} ${x.notes}`.toLowerCase().includes(q));$("#materialLibrary").innerHTML=filtered.map(x=>{const tags=[x.grade,x.skill,x.topic,x.unit,...String(x.tags||"").split(",")].map(v=>String(v||"").trim()).filter(Boolean);return`<article class="material-card"><div class="material-header"><span class="type-pill">${escapeHTML(x.type||"Resource")}</span><button data-delete-material="${x.id}">Delete</button></div><h4>${escapeHTML(x.title)}</h4><div class="tag-row">${tags.map(t=>`<span class="tag">${escapeHTML(t)}</span>`).join("")}</div><p>${escapeHTML(x.notes||"No notes added.")}</p>${x.url?`<a href="${safeUrl(x.url)}" target="_blank" rel="noreferrer">Open resource ↗</a>`:""}</article>`}).join("")||'<div class="empty-state">No resources match this filter.</div>';$$('[data-delete-material]').forEach(b=>b.addEventListener('click',()=>{data.materials=data.materials.filter(x=>x.id!==b.dataset.deleteMaterial);persist("Resource deleted")}))}
function openLessonDialog(id=null,preset=null){const x=data.lessons.find(v=>v.id===id);$("#lessonForm").reset();$("#lessonDuration").value=60;$("#lessonDate").value=toISODate(new Date());$("#lessonTime").value="09:00";$("#lessonId").value=x?.id||"";$("#lessonDialogTitle").textContent=x?"Edit lesson":"Add lesson";$("#deleteLessonButton").classList.toggle("hidden",!x);if(x){$("#lessonTitle").value=x.title;$("#lessonDate").value=x.date;$("#lessonTime").value=x.time;$("#lessonDuration").value=x.duration;$("#lessonType").value=x.type;$("#lessonLearner").value=x.learner||"";$("#lessonObjective").value=x.objective||"";$("#lessonNotes").value=x.notes||"";$("#lessonMaterialUrl").value=x.materialUrl||""}else if(preset)$("#lessonType").value=preset;$("#lessonDialog").showModal()}
function affectedByBump(id){const selected=data.lessons.find(x=>x.id===id);if(!selected)return[];const key=`${selected.date}T${selected.time}`,seq=selected.learner||selected.type;return data.lessons.filter(x=>(x.learner||x.type)===seq&&`${x.date}T${x.time}`>=key)}
function openBumpDialog(id){$("#bumpLessonId").value=id;$("#bumpDays").value="1";$("#skipWeekends").checked=true;const items=affectedByBump(id),selected=data.lessons.find(x=>x.id===id);$("#bumpImpactText").textContent=`This will move ${items.length} lesson${items.length===1?"":"s"} in “${selected?.learner||selected?.type||"this sequence"}”. You can undo the bump afterward.`;$("#bumpDialog").showModal()}
function shiftDate(dateString,days,skip){let d=parseLocalDate(dateString),left=days;while(left>0){d=addDays(d,1);if(!skip||![0,6].includes(d.getDay()))left--}return toISODate(d)}
function bumpSchedule(id,days,skip){const items=affectedByBump(id);if(!items.length)return;const changes=items.map(x=>({id:x.id,beforeDate:x.date,afterDate:shiftDate(x.date,days,skip)}));data.lessons=data.lessons.map(x=>{const c=changes.find(v=>v.id===x.id);return c?{...x,date:c.afterDate}:x});localStorage.setItem(UNDO_BUMP_KEY,JSON.stringify({createdAt:Date.now(),changes}));persist(`${changes.length} lesson${changes.length===1?"":"s"} bumped`);showToast(`${changes.length} lesson${changes.length===1?"":"s"} moved`,"Undo",undoLastBump)}
function undoLastBump(){let record;try{record=JSON.parse(localStorage.getItem(UNDO_BUMP_KEY)||"null")}catch{}if(!record?.changes?.length){showToast("No bump to undo");return}let restored=0,skipped=0;data.lessons=data.lessons.map(x=>{const c=record.changes.find(v=>v.id===x.id);if(!c)return x;if(x.date===c.afterDate){restored++;return{...x,date:c.beforeDate}}skipped++;return x});localStorage.removeItem(UNDO_BUMP_KEY);persist(`Bump undone: ${restored} restored${skipped?`, ${skipped} manually changed`:""}`)}
function updateUndoButtons(){const bump=localStorage.getItem(UNDO_BUMP_KEY),imp=localStorage.getItem(UNDO_IMPORT_KEY);$("#undoBumpButton").disabled=!bump;$("#undoImportButton").disabled=!imp}
function exportData(){const blob=new Blob([JSON.stringify({...data,exportedAt:new Date().toISOString(),format:"Classroom backup"},null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`classroom-backup-${toISODate(new Date())}.json`;a.click();URL.revokeObjectURL(a.href);showToast("Backup exported")}
function showToast(text,actionLabel=null,action=null){const t=$("#toast"),b=$("#toastAction");$("#toastText").textContent=text;b.classList.toggle("hidden",!actionLabel);b.textContent=actionLabel||"";b.onclick=action||null;t.classList.add("show");clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>t.classList.remove("show"),actionLabel?6000:2400)}
function normalizeHeader(v){return String(v||"").trim().toLowerCase().replace(/[\s_-]+/g," ")}
function autoMap(headers,category){const fields=Object.keys(categoryConfig[category].fields),used=new Set(),map={};headers.forEach(h=>{const n=normalizeHeader(h);let best="";for(const f of fields){if(used.has(f))continue;const list=[f,...(aliases[f]||[])].map(normalizeHeader);if(list.includes(n)||list.some(a=>a&&n.includes(a))){best=f;break}}if(best)used.add(best);map[h]=best});return map}
function inferCategory(headers,fileName,rows){const all=headers.map(normalizeHeader).join(" ")+" "+normalizeHeader(fileName);const scores={lesson:0,calendar:0,library:0,student:0,memory:0,template:0};const hit=(cat,terms,points=2)=>terms.forEach(t=>{if(all.includes(normalizeHeader(t)))scores[cat]+=points});hit("lesson",["lesson","start time","duration","objective","learner","课程","上课时间"],2);hit("calendar",["holiday","school closed","calendar","end date","放假","校历"],3);hit("library",["resource","url","link","skill","topic","worksheet","slides","资源","链接"],2);hit("student",["student name","grade","interests","goals","学生姓名","兴趣"],2);hit("memory",["observation","next step","teaching memory","教学记录","下一步"],3);hit("template",["template","activities","procedures","模版","教学活动"],3);if(headers.some(h=>["date","日期"].includes(normalizeHeader(h))))scores.lesson++;return Object.entries(scores).sort((a,b)=>b[1]-a[1])[0][0]}
function parseCSV(text){const rows=[];let row=[],field="",quoted=false;for(let i=0;i<text.length;i++){const c=text[i],n=text[i+1];if(c==='"'&&quoted&&n==='"'){field+='"';i++}else if(c==='"')quoted=!quoted;else if(c===','&&!quoted){row.push(field);field=""}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&n==='\n')i++;row.push(field);field="";if(row.some(v=>String(v).trim()!==""))rows.push(row);row=[]}else field+=c}row.push(field);if(row.some(v=>String(v).trim()!==""))rows.push(row);if(!rows.length)return[];const headers=rows[0].map((h,i)=>String(h).trim()||`Column ${i+1}`);return rows.slice(1).map(r=>Object.fromEntries(headers.map((h,i)=>[h,r[i]??""])))}
function parseICS(text){const events=[];for(const block of text.replace(/\r?\n[ \t]/g,"").split("BEGIN:VEVENT").slice(1)){const get=k=>{const m=block.match(new RegExp(`^${k}(?:;[^:]*)?:(.*)$`,`mi`));return m?m[1].trim():""},start=get("DTSTART"),end=get("DTEND"),date=start.slice(0,8),time=start.includes("T")?start.slice(9,13):"";events.push({"Event title":get("SUMMARY")||"Calendar event","Date":date?`${date.slice(0,4)}-${date.slice(4,6)}-${date.slice(6,8)}`:"","Start time":time?`${time.slice(0,2)}:${time.slice(2,4)}`:"","End date":end.slice(0,8)?`${end.slice(0,4)}-${end.slice(4,6)}-${end.slice(6,8)}`:"","Notes":get("DESCRIPTION"),"URL":get("URL")})}return events}
async function parseFile(file){const ext=file.name.split('.').pop().toLowerCase();if(ext==="csv")return parseCSV(await file.text());if(ext==="ics")return parseICS(await file.text());if(ext==="json"){const obj=JSON.parse(await file.text());if(obj&&Array.isArray(obj.lessons)&&Array.isArray(obj.materials))return{backup:obj};return Array.isArray(obj)?obj:(Array.isArray(obj.records)?obj.records:[obj])}if(["xlsx","xls"].includes(ext)){if(typeof XLSX==="undefined")throw new Error("Excel reader did not load. Refresh the page and try again.");const wb=XLSX.read(await file.arrayBuffer(),{type:"array",cellDates:false});return XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]],{defval:"",raw:false})}throw new Error("Unsupported file type")}
async function handleImportFile(file){try{$("#fileSummary").classList.remove("hidden");$("#fileSummary").textContent=`Reading ${file.name}…`;const parsed=await parseFile(file);if(parsed?.backup){pendingImport={fileName:file.name,backup:normalizeData(parsed.backup)};$("#fileSummary").innerHTML=`<strong>${escapeHTML(file.name)}</strong><br>Classroom backup detected.`;$("#mappingArea").innerHTML='<div class="privacy-banner"><strong>Full backup</strong><span>This will restore lessons, library resources, imports, and other local data from the file.</span></div>';$("#previewArea").innerHTML=`<div class="file-summary">${pendingImport.backup.lessons.length} lessons · ${pendingImport.backup.materials.length} resources · ${pendingImport.backup.imports.length} import records</div>`;$("#confirmImportButton").disabled=false;$("#confirmImportButton").textContent="Restore backup";$("#importCategory").disabled=true;$("#importMode").disabled=true;return}const rows=parsed.filter(x=>x&&typeof x==="object"&&!Array.isArray(x)),headers=[...new Set(rows.flatMap(r=>Object.keys(r)))],category=inferCategory(headers,file.name,rows);pendingImport={fileName:file.name,rows,headers,category,mapping:autoMap(headers,category)};$("#fileSummary").innerHTML=`<strong>${escapeHTML(file.name)}</strong><br>${rows.length} rows · ${headers.length} columns · suggested: ${categoryConfig[category].label}`;$("#importCategory").disabled=false;$("#importMode").disabled=false;$("#importCategory").value=category;$("#confirmImportButton").disabled=rows.length===0;$("#confirmImportButton").textContent="Import records";renderMapping();renderPreview()}catch(e){pendingImport=null;$("#fileSummary").classList.remove("hidden");$("#fileSummary").textContent=`Could not read file: ${e.message}`;$("#confirmImportButton").disabled=true;showToast("Import file could not be read")}}
function renderMapping(){if(!pendingImport?.headers)return;const cfg=categoryConfig[pendingImport.category];$("#mappingArea").innerHTML=`<table class="mapping-table"><thead><tr><th>File column</th><th>Maps to</th></tr></thead><tbody>${pendingImport.headers.map(h=>`<tr><td>${escapeHTML(h)}</td><td><select data-map-header="${escapeHTML(h)}"><option value="">Ignore this column</option>${Object.entries(cfg.fields).map(([k,l])=>`<option value="${k}" ${pendingImport.mapping[h]===k?"selected":""}>${escapeHTML(l)}</option>`).join("")}</select></td></tr>`).join("")}</tbody></table>`;$$('[data-map-header]').forEach(s=>s.addEventListener('change',()=>{pendingImport.mapping[s.dataset.mapHeader]=s.value;renderPreview()}))}
function mappedRows(){if(!pendingImport?.rows)return[];return pendingImport.rows.map(row=>{const out={};for(const[h,f]of Object.entries(pendingImport.mapping))if(f&&String(row[h]??"").trim()!=="")out[f]=row[h];return out})}
function renderPreview(){if(!pendingImport?.rows)return;const rows=mappedRows(),cfg=categoryConfig[pendingImport.category],mappedFields=[...new Set(Object.values(pendingImport.mapping).filter(Boolean))],valid=rows.filter(r=>cfg.required.every(f=>String(r[f]??"").trim()));const missing=rows.length-valid.length;$("#importWarnings").innerHTML=(missing?`<div class="warning">${missing} row${missing===1?"":"s"} are missing required mapped fields and will be skipped.</div>`:"")+(mappedFields.length===0?'<div class="warning">Map at least one file column before importing.</div>':"");if(!rows.length){$("#previewArea").innerHTML='<div class="empty-state">No rows found.</div>';return}const fields=mappedFields.length?mappedFields:Object.keys(cfg.fields).slice(0,4);$("#previewArea").innerHTML=`<table class="preview-table"><thead><tr>${fields.map(f=>`<th>${escapeHTML(cfg.fields[f]||f)}</th>`).join("")}</tr></thead><tbody>${rows.slice(0,10).map(r=>`<tr>${fields.map(f=>`<td>${escapeHTML(r[f]??"")}</td>`).join("")}</tr>`).join("")}</tbody></table><p class="planner-note">Showing ${Math.min(10,rows.length)} of ${rows.length} rows.</p>`;$("#confirmImportButton").disabled=mappedFields.length===0}
function cleanImported(category,row,batchId){const base={id:crypto.randomUUID(),importBatchId:batchId,sourceFile:pendingImport.fileName,importedAt:Date.now()};if(category==="lesson")return{...base,title:String(row.title||"").trim(),date:normalizeDate(row.date),time:normalizeTime(row.time),duration:Number(row.duration)||60,type:String(row.type||"Class").trim(),learner:String(row.learner||"").trim(),objective:String(row.objective||"").trim(),notes:String(row.notes||"").trim(),materialUrl:String(row.materialUrl||"").trim()};if(category==="calendar")return{...base,title:String(row.title||"").trim(),date:normalizeDate(row.date),endDate:normalizeDate(row.endDate)||normalizeDate(row.date),type:String(row.type||"School event").trim(),notes:String(row.notes||"").trim()};if(category==="library")return{...base,title:String(row.title||"").trim(),type:String(row.type||"Other").trim(),url:String(row.url||"").trim(),grade:String(row.grade||"").trim(),skill:String(row.skill||"").trim(),topic:String(row.topic||"").trim(),unit:String(row.unit||"").trim(),tags:String(row.tags||"").trim(),notes:String(row.notes||"").trim(),createdAt:Date.now()};return{...base,...Object.fromEntries(Object.entries(row).map(([k,v])=>[k,String(v??"").trim()]))}}
function recordKey(category,x){if(category==="lesson")return`${x.date}|${x.time}|${x.title}|${x.learner}`.toLowerCase();if(category==="calendar")return`${x.date}|${x.title}`.toLowerCase();if(category==="library")return`${x.title}|${x.url}`.toLowerCase();if(category==="student")return`${x.name}|${x.grade}|${x.group}`.toLowerCase();if(category==="memory")return`${x.learner}|${x.date}|${x.category}|${x.observation}`.toLowerCase();return`${x.title}|${x.type}`.toLowerCase()}
function applyImport(){if(!pendingImport)return;if(pendingImport.backup){if(!confirm("Restore this backup? Current local data will be replaced. You can undo the restore once."))return;localStorage.setItem(UNDO_IMPORT_KEY,JSON.stringify({snapshot:data,label:"backup restore"}));data=normalizeData(pendingImport.backup);data.imports.push({id:crypto.randomUUID(),fileName:pendingImport.fileName,category:"backup",mode:"restore",count:data.lessons.length+data.materials.length,createdAt:Date.now()});localStorage.setItem(STORAGE_KEY,JSON.stringify(data));resetImportUI();renderAll();showToast("Backup restored","Undo",undoLastImport);return}const category=pendingImport.category,cfg=categoryConfig[category],batchId=crypto.randomUUID(),rows=mappedRows().filter(r=>cfg.required.every(f=>String(r[f]??"").trim())).map(r=>cleanImported(category,r,batchId)).filter(r=>category!=="lesson"||r.date),mode=$("#importMode").value;if(!rows.length){showToast("No valid records to import");return}if(mode==="replace"&&!confirm(`Replace all existing ${cfg.label.toLowerCase()} with ${rows.length} imported records?`))return;localStorage.setItem(UNDO_IMPORT_KEY,JSON.stringify({snapshot:data,label:`${pendingImport.fileName} import`}));const collection=cfg.collection;if(mode==="replace")data[collection]=rows;else if(mode==="add")data[collection].push(...rows);else{const existing=new Map(data[collection].map((x,i)=>[recordKey(category,x),i]));for(const row of rows){const key=recordKey(category,row);if(existing.has(key)){const i=existing.get(key);data[collection][i]={...data[collection][i],...Object.fromEntries(Object.entries(row).filter(([,v])=>v!==""))}}else{existing.set(key,data[collection].length);data[collection].push(row)}}}data.imports.push({id:batchId,fileName:pendingImport.fileName,category,mode,count:rows.length,createdAt:Date.now()});localStorage.setItem(STORAGE_KEY,JSON.stringify(data));resetImportUI();renderAll();showToast(`${rows.length} ${cfg.label.toLowerCase()} imported`,"Undo",undoLastImport)}
function undoLastImport(){let u;try{u=JSON.parse(localStorage.getItem(UNDO_IMPORT_KEY)||"null")}catch{}if(!u?.snapshot){showToast("No import to undo");return}data=normalizeData(u.snapshot);localStorage.setItem(STORAGE_KEY,JSON.stringify(data));localStorage.removeItem(UNDO_IMPORT_KEY);renderAll();showToast("Last import undone")}
function resetImportUI(){pendingImport=null;$("#importFile").value="";$("#fileSummary").classList.add("hidden");$("#mappingArea").innerHTML='<div class="empty-state compact">Choose a file to create a field map.</div>';$("#previewArea").innerHTML='<div class="empty-state">A preview will appear here before anything is saved.</div>';$("#importWarnings").innerHTML="";$("#importCategory").disabled=true;$("#importMode").disabled=true;$("#confirmImportButton").disabled=true;$("#confirmImportButton").textContent="Import records"}
function renderImportHistory(){const h=[...data.imports].sort((a,b)=>b.createdAt-a.createdAt);$("#importHistory").innerHTML=h.map(x=>`<div class="history-item"><div><strong>${escapeHTML(x.fileName||"Imported data")}</strong><p>${escapeHTML(categoryConfig[x.category]?.label||x.category||"Backup")} · ${escapeHTML(x.mode||"add")}</p></div><div><strong>${x.count||0}</strong><small> records<br>${new Date(x.createdAt).toLocaleString()}</small></div></div>`).join("")||'<div class="empty-state compact">No imports yet.</div>'}
$$('[data-close-dialog]').forEach(b=>b.addEventListener('click',()=>b.closest('dialog').close()));$$('.nav-item').forEach(b=>b.addEventListener('click',()=>switchView(b.dataset.view)));$$('[data-go-to]').forEach(b=>b.addEventListener('click',()=>switchView(b.dataset.goTo)));$("#addLessonButton").addEventListener('click',()=>openLessonDialog());$("#addSessionButton").addEventListener('click',()=>openLessonDialog(null,"One-on-one"));$("#addMaterialButton").addEventListener('click',()=>$("#materialDialog").showModal());$("#exportButton").addEventListener('click',exportData);$("#undoBumpButton").addEventListener('click',undoLastBump);$("#undoImportButton").addEventListener('click',undoLastImport);$("#materialSearch").addEventListener('input',renderLibrary);$("#materialTypeFilter").addEventListener('change',renderLibrary);$("#materialSkillFilter").addEventListener('change',renderLibrary);$("#previousWeek").addEventListener('click',()=>{weekStart=addDays(weekStart,-7);renderAll()});$("#nextWeek").addEventListener('click',()=>{weekStart=addDays(weekStart,7);renderAll()});$("#todayButton").addEventListener('click',()=>{weekStart=getMonday(new Date());renderAll()});
$("#lessonForm").addEventListener('submit',e=>{e.preventDefault();const x={id:$("#lessonId").value||crypto.randomUUID(),title:$("#lessonTitle").value.trim(),date:$("#lessonDate").value,time:$("#lessonTime").value,duration:Number($("#lessonDuration").value),type:$("#lessonType").value,learner:$("#lessonLearner").value.trim(),objective:$("#lessonObjective").value.trim(),notes:$("#lessonNotes").value.trim(),materialUrl:$("#lessonMaterialUrl").value.trim()},i=data.lessons.findIndex(v=>v.id===x.id);if(i>=0)data.lessons[i]=x;else data.lessons.push(x);$("#lessonDialog").close();persist(i>=0?"Lesson updated":"Lesson added")});
$("#deleteLessonButton").addEventListener('click',()=>{data.lessons=data.lessons.filter(x=>x.id!==$("#lessonId").value);$("#lessonDialog").close();persist("Lesson deleted")});
$("#materialForm").addEventListener('submit',e=>{e.preventDefault();data.materials.push({id:crypto.randomUUID(),title:$("#materialTitle").value.trim(),type:$("#materialType").value,grade:$("#materialGrade").value.trim(),skill:$("#materialSkill").value.trim(),topic:$("#materialTopic").value.trim(),unit:$("#materialUnit").value.trim(),tags:$("#materialTags").value.trim(),url:$("#materialUrl").value.trim(),notes:$("#materialNotes").value.trim(),createdAt:Date.now()});e.target.reset();$("#materialDialog").close();persist("Resource added")});
$("#bumpForm").addEventListener('submit',e=>{e.preventDefault();bumpSchedule($("#bumpLessonId").value,Number($("#bumpDays").value),$("#skipWeekends").checked);$("#bumpDialog").close()});
$("#importFile").addEventListener('change',e=>{if(e.target.files[0])handleImportFile(e.target.files[0])});$("#importCategory").addEventListener('change',e=>{if(!pendingImport?.rows)return;pendingImport.category=e.target.value;pendingImport.mapping=autoMap(pendingImport.headers,pendingImport.category);renderMapping();renderPreview()});$("#confirmImportButton").addEventListener('click',applyImport);const dz=$("#dropZone");['dragenter','dragover'].forEach(ev=>dz.addEventListener(ev,e=>{e.preventDefault();dz.classList.add('dragover')}));['dragleave','drop'].forEach(ev=>dz.addEventListener(ev,e=>{e.preventDefault();dz.classList.remove('dragover')}));dz.addEventListener('drop',e=>{const f=e.dataTransfer.files[0];if(f)handleImportFile(f)});
renderAll();