"use strict";

const UNDO_PLAYBOOK_KEY_V6="classroomUndoPlaybookV1";
let playbookTabV6="Daily",activePlaybookRunV6=null;
const PLAYBOOK_CATEGORY_LABELS_V6={Daily:"Daily Routine",Teaching:"Teaching Routine",Operational:"Operational Routine"};
function ensurePlaybookV6(){if(!Array.isArray(data.playbookRoutines))data.playbookRoutines=[];if(!Array.isArray(data.playbookRuns))data.playbookRuns=[];data.playbookRoutines=data.playbookRoutines.map(x=>({...x,id:x.id||crypto.randomUUID(),title:String(x.title||"Routine").trim(),category:normalizeRoutineCategory(x.category),status:normalizeRoutineStatus(x.status),purpose:String(x.purpose||"").trim(),whenToUse:String(x.whenToUse||"").trim(),frequency:String(x.frequency||"").trim(),steps:normalizeRoutineSteps(x.steps),cues:String(x.cues||"").trim(),materials:String(x.materials||"").trim(),recovery:String(x.recovery||"").trim(),materialIds:Array.isArray(x.materialIds)?[...new Set(x.materialIds.filter(Boolean))]:[],tags:String(x.tags||"").trim(),pinned:Boolean(x.pinned),createdAt:Number(x.createdAt)||Date.now(),updatedAt:Number(x.updatedAt||x.createdAt)||Date.now(),lastRunAt:Number(x.lastRunAt)||0}));}
function playbookSnapshotV6(label){ensurePlaybookV6();localStorage.setItem(UNDO_PLAYBOOK_KEY_V6,JSON.stringify({label,routines:structuredClone(data.playbookRoutines),runs:structuredClone(data.playbookRuns),lessonLinks:(data.lessons||[]).map(x=>({id:x.id,routineIds:[...(x.routineIds||[])]})),createdAt:Date.now()}))}
function savePlaybookV6(message){localStorage.setItem(STORAGE_KEY,JSON.stringify(data));renderAll();showToast(message)}
function undoPlaybookV6(){let u;try{u=JSON.parse(localStorage.getItem(UNDO_PLAYBOOK_KEY_V6)||"null")}catch{}if(!u?.routines){showToast("No playbook action to undo");return}data.playbookRoutines=u.routines;data.playbookRuns=u.runs||[];const map=new Map((u.lessonLinks||[]).map(x=>[x.id,x.routineIds||[]]));(data.lessons||[]).forEach(x=>x.routineIds=map.get(x.id)||[]);localStorage.setItem(STORAGE_KEY,JSON.stringify(data));localStorage.removeItem(UNDO_PLAYBOOK_KEY_V6);renderAll();showToast("Playbook action undone")}
function playbookTextV6(x){return `${x.title} ${x.category} ${x.status} ${x.purpose} ${x.whenToUse} ${x.frequency} ${(x.steps||[]).join(" ")} ${x.cues} ${x.materials} ${x.recovery} ${x.tags}`.toLowerCase()}
function routineMaterialsV6(x){const ids=new Set(x.materialIds||[]);return(data.materials||[]).filter(m=>ids.has(m.id))}
function routineLinkedLessonsV6(x){return(data.lessons||[]).filter(l=>(l.routineIds||[]).includes(x.id))}
function playbookFiltersV6(){return{q:$("#playbookSearchInput").value.trim().toLowerCase(),status:$("#playbookStatusFilter").value,sort:$("#playbookSort").value,pinned:$("#playbookPinnedOnly").checked}}
function filteredPlaybookV6(){const f=playbookFiltersV6();let list=(data.playbookRoutines||[]).filter(x=>x.category===playbookTabV6&&(f.status==="all"||x.status===f.status)&&(!f.pinned||x.pinned)&&(!f.q||playbookTextV6(x).includes(f.q)));if(f.sort==="title")list.sort((a,b)=>a.title.localeCompare(b.title));else if(f.sort==="updated")list.sort((a,b)=>b.updatedAt-a.updatedAt);else if(f.sort==="used")list.sort((a,b)=>(b.lastRunAt||0)-(a.lastRunAt||0)||a.title.localeCompare(b.title));else list.sort((a,b)=>Number(b.pinned)-Number(a.pinned)||a.title.localeCompare(b.title));return list}
function playbookStatusClassV6(v){return String(v||"").toLowerCase().replaceAll(" ","-")}
function renderPlaybookCardV6(x){const resources=routineMaterialsV6(x),lessons=routineLinkedLessonsV6(x),steps=x.steps||[],tags=String(x.tags||"").split(",").map(v=>v.trim()).filter(Boolean);return`<article class="playbook-routine-card ${x.pinned?"pinned":""}"><div class="playbook-card-head"><div><div class="playbook-pill-row"><span class="playbook-category-pill ${x.category.toLowerCase()}">${PLAYBOOK_CATEGORY_LABELS_V6[x.category]}</span><span class="playbook-status-pill ${playbookStatusClassV6(x.status)}">${escapeHTML(x.status)}</span>${x.pinned?'<span class="playbook-pin">★ Pinned</span>':""}</div><h4>${escapeHTML(x.title)}</h4><p>${escapeHTML([x.whenToUse,x.frequency].filter(Boolean).join(" · ")||"No trigger or frequency added.")}</p></div><button class="icon-button compact" type="button" data-edit-routine="${x.id}" aria-label="Edit ${escapeHTML(x.title)}">•••</button></div>${x.purpose?`<div class="playbook-purpose"><span>Purpose</span><p>${escapeHTML(x.purpose)}</p></div>`:""}<ol class="playbook-step-preview">${steps.slice(0,4).map(s=>`<li>${escapeHTML(s)}</li>`).join("")}${steps.length>4?`<li class="more-step">+ ${steps.length-4} more steps</li>`:""}</ol>${x.cues?`<div class="playbook-cue"><span>Teacher cue</span><p>${escapeHTML(x.cues)}</p></div>`:""}<div class="playbook-card-meta"><span>${steps.length} step${steps.length===1?"":"s"}</span><span>${resources.length} resource${resources.length===1?"":"s"}</span><span>${lessons.length} linked lesson${lessons.length===1?"":"s"}</span></div>${tags.length?`<div class="tag-row">${tags.slice(0,6).map(t=>`<span class="tag">${escapeHTML(t)}</span>`).join("")}</div>`:""}<div class="playbook-card-actions"><button class="button button-primary button-small" type="button" data-run-routine="${x.id}" ${steps.length?"":"disabled"}>Run checklist</button><button class="button button-secondary button-small" type="button" data-link-routine="${x.id}">Add to lesson</button><button class="button button-secondary button-small" type="button" data-duplicate-routine="${x.id}">Duplicate</button><button class="text-button" type="button" data-edit-routine="${x.id}">Edit</button></div></article>`}
function renderPlaybookV6(){const view=$("#playbookView");if(!view)return;ensurePlaybookV6();$$('[data-playbook-tab]').forEach(b=>b.classList.toggle("active",b.dataset.playbookTab===playbookTabV6));const today=toISODate(new Date()),month=today.slice(0,7),list=filteredPlaybookV6();$("#playbookActiveCount").textContent=data.playbookRoutines.filter(x=>x.status==="Active").length;$("#playbookPinnedCount").textContent=data.playbookRoutines.filter(x=>x.pinned).length;$("#playbookMonthRunsCount").textContent=data.playbookRuns.filter(x=>new Date(x.completedAt).toISOString().slice(0,7)===month).length;$("#playbookDraftCount").textContent=data.playbookRoutines.filter(x=>x.status==="Draft").length;$("#playbookResultCount").textContent=`${list.length} routine${list.length===1?"":"s"}`;$("#undoPlaybookButton").disabled=!localStorage.getItem(UNDO_PLAYBOOK_KEY_V6);$("#playbookRoutineList").innerHTML=list.map(renderPlaybookCardV6).join("")||'<div class="empty-state">No routines match this category and filter. Add a routine or import a Playbook CSV.</div>';const recent=[...data.playbookRuns].sort((a,b)=>b.completedAt-a.completedAt).slice(0,8);$("#playbookRecentRuns").innerHTML=recent.map(x=>`<div class="playbook-run-row"><div><strong>${escapeHTML(x.routineTitle||"Routine")}</strong><span>${escapeHTML(PLAYBOOK_CATEGORY_LABELS_V6[x.category]||x.category)} · ${new Date(x.completedAt).toLocaleString()}</span>${x.notes?`<small>${escapeHTML(x.notes)}</small>`:""}</div><div><strong>${x.completedSteps}/${x.totalSteps}</strong><span>steps completed</span></div></div>`).join("")||'<div class="empty-state compact">No routine runs recorded. Running a checklist is optional.</div>'}
function fillPlaybookMaterialOptionsV6(selected=[]){const chosen=new Set(selected);$("#playbookRoutineMaterialIds").innerHTML=[...(data.materials||[])].sort((a,b)=>a.title.localeCompare(b.title)).map(x=>`<option value="${x.id}" ${chosen.has(x.id)?"selected":""}>${escapeHTML(x.title)} — ${escapeHTML(x.type||"Resource")}</option>`).join("")||'<option disabled>No Library resources yet</option>'}
function openPlaybookDialogV6(id=null,{duplicate=false}={}){ensurePlaybookV6();const source=data.playbookRoutines.find(x=>x.id===id),x=source&&duplicate?{...structuredClone(source),id:"",title:`${source.title} copy`,pinned:false}:source;$("#playbookRoutineForm").reset();$("#playbookRoutineId").value=x?.id||"";$("#playbookRoutineDialogTitle").textContent=x?.id?"Edit routine":duplicate?"Duplicate routine":"Add routine";$("#deletePlaybookRoutineButton").classList.toggle("hidden",!x?.id);$("#playbookRoutineCategory").value=x?.category||playbookTabV6;$("#playbookRoutineStatus").value=x?.status||"Active";$("#playbookRoutineTitle").value=x?.title||"";$("#playbookRoutinePurpose").value=x?.purpose||"";$("#playbookRoutineWhen").value=x?.whenToUse||"";$("#playbookRoutineFrequency").value=x?.frequency||"";$("#playbookRoutineSteps").value=(x?.steps||[]).join("\n");$("#playbookRoutineCues").value=x?.cues||"";$("#playbookRoutineMaterials").value=x?.materials||"";$("#playbookRoutineRecovery").value=x?.recovery||"";fillPlaybookMaterialOptionsV6(x?.materialIds||[]);$("#playbookRoutineTags").value=x?.tags||"";$("#playbookRoutinePinned").checked=Boolean(x?.pinned);$("#playbookRoutineDialog").showModal()}
function openPlaybookRunV6(id){const x=data.playbookRoutines.find(v=>v.id===id);if(!x)return;activePlaybookRunV6=x.id;$("#playbookRunRoutineId").value=x.id;$("#playbookRunTitle").textContent=x.title;$("#playbookRunSubtitle").textContent=[PLAYBOOK_CATEGORY_LABELS_V6[x.category],x.whenToUse,x.frequency].filter(Boolean).join(" · ");$("#playbookRunNotes").value="";$("#playbookRunChecklist").innerHTML=(x.steps||[]).map((step,i)=>`<label class="playbook-run-step"><input type="checkbox" data-run-step="${i}"/><span><strong>${i+1}</strong>${escapeHTML(step)}</span></label>`).join("")||'<div class="empty-state">This routine has no checklist steps yet.</div>';$("#playbookRunDialog").showModal()}
function finishPlaybookRunV6(){const x=data.playbookRoutines.find(v=>v.id===$("#playbookRunRoutineId").value);if(!x)return;const checked=$$('#playbookRunChecklist [data-run-step]:checked').length,total=(x.steps||[]).length;playbookSnapshotV6("Record routine run");const now=Date.now();data.playbookRuns.push({id:crypto.randomUUID(),routineId:x.id,routineTitle:x.title,category:x.category,completedSteps:checked,totalSteps:total,notes:$("#playbookRunNotes").value.trim(),completedAt:now});x.lastRunAt=now;x.updatedAt=now;$("#playbookRunDialog").close();savePlaybookV6("Routine run recorded")}
function openPlaybookLinkLessonV6(id){const x=data.playbookRoutines.find(v=>v.id===id);if(!x)return;$("#playbookLinkRoutineId").value=x.id;$("#playbookLinkLessonTitle").textContent=`Add “${x.title}” to a lesson`;const lessons=[...(data.lessons||[])].sort((a,b)=>`${a.date}T${a.time}`.localeCompare(`${b.date}T${b.time}`));$("#playbookLinkLessonId").innerHTML=lessons.map(l=>`<option value="${l.id}" ${(l.routineIds||[]).includes(x.id)?"disabled":""}>${escapeHTML(l.date)} · ${escapeHTML(l.time||"")} · ${escapeHTML(l.title)}${(l.routineIds||[]).includes(x.id)?" — already linked":""}</option>`).join("")||'<option value="">No lessons available</option>';const available=lessons.find(l=>!(l.routineIds||[]).includes(x.id));if(available)$("#playbookLinkLessonId").value=available.id;$("#confirmPlaybookLinkButton").disabled=!available;$("#playbookLinkLessonDialog").showModal()}
function confirmPlaybookLinkV6(){const routineId=$("#playbookLinkRoutineId").value,lesson=data.lessons.find(x=>x.id===$("#playbookLinkLessonId").value);if(!routineId||!lesson)return;playbookSnapshotV6("Link routine to lesson");lesson.routineIds=[...new Set([...(lesson.routineIds||[]),routineId])];$("#playbookLinkLessonDialog").close();savePlaybookV6("Routine added to lesson")}
function openLessonPlaybookV6(lessonId){const lesson=data.lessons.find(x=>x.id===lessonId);if(!lesson)return;$("#lessonPlaybookLessonId").value=lesson.id;$("#lessonPlaybookTitle").textContent=lesson.title;$("#lessonPlaybookSubtitle").textContent=`${lesson.date} · ${lesson.time||""}`;const routines=(lesson.routineIds||[]).map(id=>data.playbookRoutines.find(x=>x.id===id)).filter(Boolean);$("#lessonPlaybookList").innerHTML=routines.map(x=>`<div class="lesson-playbook-row"><div><strong>${escapeHTML(x.title)}</strong><span>${escapeHTML(PLAYBOOK_CATEGORY_LABELS_V6[x.category])} · ${(x.steps||[]).length} steps</span></div><div><button class="button button-primary button-small" type="button" data-run-linked-routine="${x.id}">Run</button><button class="button button-secondary button-small" type="button" data-edit-linked-routine="${x.id}">Edit</button><button class="text-button danger-text" type="button" data-remove-linked-routine="${x.id}">Remove</button></div></div>`).join("")||'<div class="empty-state">No routines are linked to this lesson.</div>';$("#lessonPlaybookDialog").showModal()}
function removeRoutineFromLessonV6(routineId){const lesson=data.lessons.find(x=>x.id===$("#lessonPlaybookLessonId").value);if(!lesson)return;playbookSnapshotV6("Remove routine from lesson");lesson.routineIds=(lesson.routineIds||[]).filter(id=>id!==routineId);localStorage.setItem(STORAGE_KEY,JSON.stringify(data));openLessonPlaybookV6(lesson.id);renderAll();showToast("Routine removed from lesson")}
function exportPlaybookV6(){const payload={type:"Classroom Playbook",version:1,exportedAt:new Date().toISOString(),playbookRoutines:data.playbookRoutines,playbookRuns:data.playbookRuns};const blob=new Blob([JSON.stringify(payload,null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`Classroom-Playbook-${toISODate(new Date())}.json`;a.click();URL.revokeObjectURL(a.href);showToast("Classroom Playbook exported")}
function downloadPlaybookTemplateV6(){const headers=["Routine Title","Routine Type","Purpose","When / Trigger","Frequency","Checklist Steps","Teacher Language / Cues","Materials or Setup","Reset / Recovery Plan","Status","Tags"],sample=["","Daily Routine","","","Daily","Step 1 | Step 2 | Step 3","","","","Active",""];const csv=[headers,sample].map(row=>row.map(v=>`"${String(v).replaceAll('"','""')}"`).join(",")).join("\n"),blob=new Blob([csv],{type:"text/csv;charset=utf-8"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="Classroom-Playbook-Import-Template.csv";a.click();URL.revokeObjectURL(a.href);showToast("Playbook CSV template downloaded")}

$$('[data-playbook-tab]').forEach(b=>b.addEventListener("click",()=>{playbookTabV6=b.dataset.playbookTab;renderPlaybookV6()}));["#playbookSearchInput","#playbookStatusFilter","#playbookSort","#playbookPinnedOnly"].forEach(sel=>$(sel).addEventListener(sel.includes("Input")?"input":"change",renderPlaybookV6));
$("#addRoutineButton").addEventListener("click",()=>openPlaybookDialogV6());$("#undoPlaybookButton").addEventListener("click",undoPlaybookV6);$("#exportPlaybookButton").addEventListener("click",exportPlaybookV6);$("#downloadPlaybookTemplateButton").addEventListener("click",downloadPlaybookTemplateV6);
$("#playbookRoutineList").addEventListener("click",e=>{const edit=e.target.closest("[data-edit-routine]");if(edit)return openPlaybookDialogV6(edit.dataset.editRoutine);const run=e.target.closest("[data-run-routine]");if(run)return openPlaybookRunV6(run.dataset.runRoutine);const link=e.target.closest("[data-link-routine]");if(link)return openPlaybookLinkLessonV6(link.dataset.linkRoutine);const duplicate=e.target.closest("[data-duplicate-routine]");if(duplicate)return openPlaybookDialogV6(duplicate.dataset.duplicateRoutine,{duplicate:true})});
$("#playbookRoutineForm").addEventListener("submit",e=>{e.preventDefault();ensurePlaybookV6();const id=$("#playbookRoutineId").value||crypto.randomUUID(),existing=data.playbookRoutines.find(x=>x.id===id),selected=[...$("#playbookRoutineMaterialIds").selectedOptions].map(o=>o.value).filter(Boolean);playbookSnapshotV6(existing?"Update routine":"Add routine");const record={id,title:$("#playbookRoutineTitle").value.trim(),category:$("#playbookRoutineCategory").value,status:$("#playbookRoutineStatus").value,purpose:$("#playbookRoutinePurpose").value.trim(),whenToUse:$("#playbookRoutineWhen").value.trim(),frequency:$("#playbookRoutineFrequency").value.trim(),steps:normalizeRoutineSteps($("#playbookRoutineSteps").value),cues:$("#playbookRoutineCues").value.trim(),materials:$("#playbookRoutineMaterials").value.trim(),recovery:$("#playbookRoutineRecovery").value.trim(),materialIds:selected,tags:$("#playbookRoutineTags").value.trim(),pinned:$("#playbookRoutinePinned").checked,createdAt:existing?.createdAt||Date.now(),updatedAt:Date.now(),lastRunAt:existing?.lastRunAt||0,sourceFile:existing?.sourceFile||"",importBatchId:existing?.importBatchId||""};const i=data.playbookRoutines.findIndex(x=>x.id===id);if(i>=0)data.playbookRoutines[i]=record;else data.playbookRoutines.push(record);playbookTabV6=record.category;$("#playbookRoutineDialog").close();switchView("playbook");savePlaybookV6(i>=0?"Routine updated":"Routine added")});
$("#deletePlaybookRoutineButton").addEventListener("click",()=>{const id=$("#playbookRoutineId").value;if(!id||!confirm("Delete this routine? It will also be removed from linked lessons."))return;playbookSnapshotV6("Delete routine");data.playbookRoutines=data.playbookRoutines.filter(x=>x.id!==id);(data.lessons||[]).forEach(x=>x.routineIds=(x.routineIds||[]).filter(r=>r!==id));$("#playbookRoutineDialog").close();savePlaybookV6("Routine deleted")});
$("#finishPlaybookRunButton").addEventListener("click",finishPlaybookRunV6);$("#confirmPlaybookLinkButton").addEventListener("click",confirmPlaybookLinkV6);
$("#lessonPlaybookList").addEventListener("click",e=>{const run=e.target.closest("[data-run-linked-routine]");if(run){$("#lessonPlaybookDialog").close();return openPlaybookRunV6(run.dataset.runLinkedRoutine)}const edit=e.target.closest("[data-edit-linked-routine]");if(edit){$("#lessonPlaybookDialog").close();switchView("playbook");return openPlaybookDialogV6(edit.dataset.editLinkedRoutine)}const remove=e.target.closest("[data-remove-linked-routine]");if(remove)return removeRoutineFromLessonV6(remove.dataset.removeLinkedRoutine)});
$("#weekGrid").addEventListener("click",e=>{const button=e.target.closest("[data-lesson-playbook]");if(button)openLessonPlaybookV6(button.dataset.lessonPlaybook)});
$("#clearPlaybookRunsButton").addEventListener("click",()=>{if(!data.playbookRuns.length)return showToast("No routine history to clear");if(!confirm("Clear the optional routine run history? Your routine templates will remain."))return;playbookSnapshotV6("Clear routine history");data.playbookRuns=[];savePlaybookV6("Routine history cleared")});
renderPlaybookV6();
